# we are extending everything from tomcat:8.0 image ...
FROM tomcat:8.0

MAINTAINER vascoalramos

# COPY path-to-your-application-war path-to-webapps-in-docker-tomcat
COPY ./target/ies-lab2-1-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/